### ISSUE TITLE
Server Crash Issue

### ISSUE THREAD

**Issue by imbennji** [poqdavid/NyxCore#1]
I am trying to use this plugin and I keep getting this crash, even with the newest 1.1 release! 

10.02 15:36:06 [Server] Server thread/INFO [Nyx[mCore[m]:  [m
10.02 15:36:06 [Server] Server thread/INFO [Nyx[mCore[m]: NyxCore[m v1.1[m[m
10.02 15:36:06 [Server] Server thread/INFO [Nyx[mCore[m]: Starting...[m
10.02 15:36:06 [Server] Server thread/INFO [Nyx[mCore[m]:  [m
10.02 15:36:06 [Server] Server thread/ERROR [minecraft/MinecraftServer]: Encountered an unexpected exception
10.02 15:36:06 [Server] INFO net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from NyxMarket (nyxmarket)
10.02 15:36:06 [Server] INFO Caused by: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: io/github/poqdavid/nyx/nyxcore/Utils/Setting/NyxMarket/NMSettings
10.02 15:36:06 [Server] INFO 	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2215) ~[minecraft_server.1.12.2.jar:?]
10.02 15:36:06 [Server] INFO 	at com.google.common.cache.LocalCache.get(LocalCache.java:4154) ~[minecraft_server.1.12.2.jar:?]
10.02 15:36:06 [Server] INFO 	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) ~[minecraft_server.1.12.2.jar:?]
10.02 15:36:06 [Server] INFO 	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) ~[minecraft_server.1.12.2.jar:?]
10.02 15:36:06 [Server] INFO 	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153) ~[minecraft_server.1.12.2.jar:?]
10.02 15:36:06 [Server] INFO 	at com.google.inject.internal.FailableCache.get(FailableCache.java:54) ~[spongeforge-1.12.2-2838-7.4.7.jar:1.12.2-2838-7.4.7]
10.02 15:36:06 [Server] INFO 	at com.google.inject.internal.ConstructorInjectorStore.get(ConstructorInjectorStore.java:49) ~[spongeforge-1.12.2-2838-7.4.7.jar:1.12.2-2838-7.4.7]
10.02 15:36:06 [Server] INFO 	at com.google.inject.internal.ConstructorBindingImpl.initialize(ConstructorBindingImpl.java:155) ~[spongeforge-1.12.2-2838-7.4.7.jar:1.12.2-2838-7.4.7]
10.02 15:36:06 [Server] INFO 	at com.google.inject.internal.InjectorImpl.initializeBinding(InjectorImpl.java:592) ~[spongeforge-1.12.2-2838-7.4.7.jar:1.12.2-2838-7.4.7]
10.02 15:36:06 [Server] INFO 	at com.google.inject.internal.AbstractBindingProcessor$Processor.initializeBinding(AbstractBindingProcessor.java:173) ~[spongeforge-1.12.2-2838-7.4.7.jar:1.12.2-2838-7.4.7]
10.02 15:36:06 [Server] INFO 	at com.google.inject.internal.AbstractBindingProcessor$Processor.lambda$scheduleInitialization$0(AbstractBindingProcessor.java:160) ~[spongeforge-1.12.2-2838-7.4.7.jar:1.12.2-2838-7.4.7]
10.02 15:36:06 [Server] INFO 	at com.google.inject.internal.ProcessedBindingData.initializeBindings(ProcessedBindingData.java:49) ~[spongeforge-1.12.2-2838-7.4.7.jar:1.12.2-2838-7.4.7]
10.02 15:36:06 [Server] INFO 	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:124) ~[spongeforge-1.12.2-2838-7.4.7.jar:1.12.2-2838-7.4.7]
10.02 15:36:06 [Server] INFO 	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:108) ~[spongeforge-1.12.2-2838-7.4.7.jar:1.12.2-2838-7.4.7]
10.02 15:36:06 [Server] INFO 	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:246) ~[spongeforge-1.12.2-2838-7.4.7.jar:1.12.2-2838-7.4.7]
10.02 15:36:06 [Server] INFO 	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:251) ~[spongeforge-1.12.2-2838-7.4.7.jar:1.12.2-2838-7.4.7]
10.02 15:36:06 [Server] INFO 	at org.spongepowered.mod.plugin.SpongeModPluginContainer.constructMod(SpongeModPluginContainer.java:282) ~[spongeforge-1.12.2-2838-7.4.7.jar:1.12.2-2838-7.4.7]
10.02 15:36:06 [Server] INFO 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312]
10.02 15:36:06 [Server] INFO 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312]
10.02 15:36:06 [Server] INFO 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
10.02 15:36:06 [Multicraft] Skipped 262 lines due to rate limit (30/s)
10.02 15:36:06 [Server] INFO Exception in thread "Server thread" [15:36:06] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Applied Energistics 2 (appliedenergistics2)
10.02 15:36:06 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: Caused by: java.lang.NullPointerException
10.02 15:36:06 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at appeng.core.AppEng.serverStopped(AppEng.java:271)
10.02 15:36:06 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10.02 15:36:06 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
10.02 15:36:06 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10.02 15:36:06 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at java.lang.reflect.Method.invoke(Method.java:498)
10.02 15:36:06 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
10.02 15:36:06 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
10.02 15:36:06 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10.02 15:36:06 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at java.lang.reflect.Method.invoke(Method.java:498)
10.02 15:36:06 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
10.02 15:36:06 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
10.02 15:36:06 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
10.02 15:36:06 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
10.02 15:36:06 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
10.02 15:36:06 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
10.02 15:36:06 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
10.02 15:36:06 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
10.02 15:36:06 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
10.02 15:36:06 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10.02 15:36:06 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
10.02 15:36:06 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10.02 15:36:06 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at java.lang.reflect.Method.invoke(Method.java:498)
10.02 15:36:06 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
10.02 15:36:06 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
10.02 15:36:06 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
10.02 15:36:06 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
10.02 15:36:06 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
10.02 15:36:06 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
10.02 15:36:06 [Multicraft] Server shut down (starting)
10.02 15:36:06 [Multicraft] Restarting crashed server in 2.0 seconds
10.02 15:36:06 [Multicraft] Server stopped

**Comment by poqdavid** [comment]
@imbennji Just pushed fixes for them NyxCore itself is fine just update them should be all good
https://github.com/poqdavid/NyxMarket/releases/tag/v1.1

**Comment by imbennji** [comment]
> @imbennji Just pushed fixes for them NyxCore itself is fine just update them should be all good https://github.com/poqdavid/NyxMarket/releases/tag/v1.1

I meant to submit this to the market plugin not the NyxCore plugin, but I updated the plugin to the newest release as of 20 minutes ago and I am still getting a crash. 

10.02 15:41:40 [Server] Server thread/INFO [Nyx[mCore[m]:  [m
10.02 15:41:40 [Server] Server thread/INFO [Nyx[mCore[m]: NyxCore[m v1.1[m[m
10.02 15:41:40 [Server] Server thread/INFO [Nyx[mCore[m]: Starting...[m
10.02 15:41:40 [Server] Server thread/INFO [Nyx[mCore[m]:  [m
10.02 15:41:40 [Server] Server thread/ERROR [minecraft/MinecraftServer]: Encountered an unexpected exception
10.02 15:41:40 [Server] INFO net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from NyxMarket (nyxmarket)
10.02 15:41:40 [Server] INFO Caused by: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: io/github/poqdavid/nyx/nyxcore/Utils/Setting/NyxMarket/NMSettings
10.02 15:41:40 [Server] INFO 	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2215) ~[minecraft_server.1.12.2.jar:?]
10.02 15:41:40 [Server] INFO 	at com.google.common.cache.LocalCache.get(LocalCache.java:4154) ~[minecraft_server.1.12.2.jar:?]
10.02 15:41:40 [Server] INFO 	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) ~[minecraft_server.1.12.2.jar:?]
10.02 15:41:40 [Server] INFO 	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) ~[minecraft_server.1.12.2.jar:?]
10.02 15:41:40 [Server] INFO 	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153) ~[minecraft_server.1.12.2.jar:?]
10.02 15:41:40 [Server] INFO 	at com.google.inject.internal.FailableCache.get(FailableCache.java:54) ~[spongeforge-1.12.2-2838-7.4.7.jar:1.12.2-2838-7.4.7]
10.02 15:41:40 [Server] INFO 	at com.google.inject.internal.ConstructorInjectorStore.get(ConstructorInjectorStore.java:49) ~[spongeforge-1.12.2-2838-7.4.7.jar:1.12.2-2838-7.4.7]
10.02 15:41:40 [Server] INFO 	at com.google.inject.internal.ConstructorBindingImpl.initialize(ConstructorBindingImpl.java:155) ~[spongeforge-1.12.2-2838-7.4.7.jar:1.12.2-2838-7.4.7]
10.02 15:41:40 [Server] INFO 	at com.google.inject.internal.InjectorImpl.initializeBinding(InjectorImpl.java:592) ~[spongeforge-1.12.2-2838-7.4.7.jar:1.12.2-2838-7.4.7]
10.02 15:41:40 [Server] INFO 	at com.google.inject.internal.AbstractBindingProcessor$Processor.initializeBinding(AbstractBindingProcessor.java:173) ~[spongeforge-1.12.2-2838-7.4.7.jar:1.12.2-2838-7.4.7]
10.02 15:41:40 [Server] INFO 	at com.google.inject.internal.AbstractBindingProcessor$Processor.lambda$scheduleInitialization$0(AbstractBindingProcessor.java:160) ~[spongeforge-1.12.2-2838-7.4.7.jar:1.12.2-2838-7.4.7]
10.02 15:41:40 [Server] INFO 	at com.google.inject.internal.ProcessedBindingData.initializeBindings(ProcessedBindingData.java:49) ~[spongeforge-1.12.2-2838-7.4.7.jar:1.12.2-2838-7.4.7]
10.02 15:41:40 [Server] INFO 	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:124) ~[spongeforge-1.12.2-2838-7.4.7.jar:1.12.2-2838-7.4.7]
10.02 15:41:40 [Server] INFO 	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:108) ~[spongeforge-1.12.2-2838-7.4.7.jar:1.12.2-2838-7.4.7]
10.02 15:41:40 [Server] INFO 	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:246) ~[spongeforge-1.12.2-2838-7.4.7.jar:1.12.2-2838-7.4.7]
10.02 15:41:40 [Server] INFO 	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:251) ~[spongeforge-1.12.2-2838-7.4.7.jar:1.12.2-2838-7.4.7]
10.02 15:41:40 [Server] INFO 	at org.spongepowered.mod.plugin.SpongeModPluginContainer.constructMod(SpongeModPluginContainer.java:282) ~[spongeforge-1.12.2-2838-7.4.7.jar:1.12.2-2838-7.4.7]
10.02 15:41:40 [Server] INFO 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312]
10.02 15:41:40 [Server] INFO 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312]
10.02 15:41:40 [Server] INFO 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
10.02 15:41:40 [Multicraft] Skipped 262 lines due to rate limit (30/s)
10.02 15:41:40 [Server] INFO Exception in thread "Server thread" [15:41:40] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Applied Energistics 2 (appliedenergistics2)
10.02 15:41:40 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: Caused by: java.lang.NullPointerException
10.02 15:41:40 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at appeng.core.AppEng.serverStopped(AppEng.java:271)
10.02 15:41:40 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10.02 15:41:40 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
10.02 15:41:40 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10.02 15:41:40 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at java.lang.reflect.Method.invoke(Method.java:498)
10.02 15:41:40 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
10.02 15:41:40 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
10.02 15:41:40 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10.02 15:41:40 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at java.lang.reflect.Method.invoke(Method.java:498)
10.02 15:41:40 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
10.02 15:41:40 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
10.02 15:41:40 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
10.02 15:41:40 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
10.02 15:41:40 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
10.02 15:41:40 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
10.02 15:41:40 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
10.02 15:41:40 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
10.02 15:41:40 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
10.02 15:41:40 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10.02 15:41:40 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
10.02 15:41:40 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10.02 15:41:40 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at java.lang.reflect.Method.invoke(Method.java:498)
10.02 15:41:40 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
10.02 15:41:40 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
10.02 15:41:40 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
10.02 15:41:40 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
10.02 15:41:40 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
10.02 15:41:40 [Server] Server thread/INFO [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
10.02 15:41:41 [Multicraft] Server shut down (starting)
10.02 15:41:41 [Multicraft] Restarting crashed server in 2.0 seconds
10.02 15:41:41 [Multicraft] Server stopped

**Comment by imbennji** [comment]
> @imbennji Just pushed fixes for them NyxCore itself is fine just update them should be all good https://github.com/poqdavid/NyxMarket/releases/tag/v1.1

I use the modpack FTB revelations and for some reason your fix did not work...

**Comment by poqdavid** [comment]
@imbennji Can you give me a list of all your mods
I tested them with forge-1.12.2-14.23.5.2860 and spongeforge-1.12.2-2838-7.4.3

**Comment by imbennji** [comment]
![Capture](https://user-images.githubusercontent.com/75706138/153501958-9af34ae2-cae3-4e70-aa1c-42c3d9c5a199.PNG)

**Comment by poqdavid** [comment]
Oh just noticed you are using an older version of NyxCore https://github.com/poqdavid/NyxCore/releases/tag/v1.5 you should update

**Comment by imbennji** [comment]
> Oh just noticed you are using an older version of NyxCore https://github.com/poqdavid/NyxCore/releases/tag/v1.5 you should update

That fixed it! sorry I did not see that version on the spongeforge. Thank you, for your help!
